version: '3.8'

services:
  web:
    depends_on:
      - api
    networks:
      - poc
    container_name: web
    build:
      context: .
    image: web
    env_file:
      - .env
    restart: always
    volumes:
      - ./:/code
      - ./node_modules:/code/node_modules
    ports:
      - ${APPLICATION_PORT}:4000
networks:
  poc:
    driver: bridge